title: LLM Arxiv Daily
description: Automatically Update LLM Papers Daily using Github Actions (Update Every 6th hours)
show_downloads: true

github:
  zip_url: https://github.com/ericma1999/llm-arxiv-daily
  another_url: https://github.com/ericma1999/llm-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: 
  github: ericma1999

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
